### ISSUE TITLE
Combat Zones do not Initialize correctly in Tearle

### ISSUE THREAD

**Issue by awiebe** [Robbroad0627/AOD1.2#6]
The game softlocks if there are no valid battle targets, and there aren't for some reason.

**Comment by awiebe** [comment]
This only seems to happen with some potential battles.  According to the console damage is being dealt by the opponent, but the appearances do not appear to spawn in.

**Comment by Robbroad0627** [comment]
Went through and fixed the naming issues.  But now it appears that combat is not working anywhere, getting the same error
**
NullReferenceException: Object reference not set to an instance of an object
BattleManager.BattleStart (System.String[] enemiesToSpawn, System.Boolean setCannotFlee) (at Assets/Scripts/Battle/BattleManager.cs:99)
BattleStarter+<StartBattleCo>d__15.MoveNext () (at Assets/Scripts/Battle/BattleStarter.cs:88)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <bb4ed9929fe04849bbe2b059cba4d31f>:0)
**
